![title](img/header.png)

## Numpy

In [2]:
import numpy as np # import library numpy dgn alias np
np.__version__ # cek versi numpy Anda

'1.13.3'

In [3]:
a = np.array([[1,2],[3,4]]) # > 1D
print(a)

#dtype parameter
a = np.array([1,2,3], dtype = complex)
print(a)

# using array-scalar type
dt = np.dtype(np.int32)
print(dt)

#int8, int16, int32, int64
#can be replaced by string 'i1','i2','i4', etc
dt = np.dtype('i4')
print(dt)

[[1 2]
 [3 4]]
[ 1.+0.j  2.+0.j  3.+0.j]
int32
int32


### NumPy – Array Attributes

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape) # get size array

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
# resize ndarray
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# menggunakan reshape utk resize ndarray
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [7]:
# ndarray.ndim – atribut array 
# untuk mengembalikan jumlah dimensi array
a = np.arange(24)
print(a)

# one dimensional array
a.ndim

# now reshape it
b = a.reshape(2,4,3)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [8]:
# numpy.itemsize   – atribut array 
# untuk mengembalikan jumlah dimensi array

# dtype of array is int8 (1 byte)
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

# dtype of array is now float32 (4 byte)
x = np.array([1,2,3,4,5], dtype = np.float32)
print(x.itemsize)

1
4


## Pandas

In [9]:
import pandas as pd # import library pandas dgn alias pd
pd.__version__ # cek versi pandas Anda

'0.20.3'

### Pandas - Membuat Series

In [10]:
# Contoh Empty Series
s = pd.Series()
print(s)

Series([], dtype: float64)


### Assign default index 0

Jika tidak ada indext yang di passing, maka akan di assign default index 0 sampai length(data)-1

In [11]:
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)

0    a
1    b
2    c
3    d
dtype: object


Mencoba untuk melewatkan( (passed) nilai index


In [12]:
data = np.array(['a','b','c','d'])
s = pd.Series(data,index=[100,101,102,103])
print(s)

100    a
101    b
102    c
103    d
dtype: object


Series dari Dictionary (Dict)

In [13]:
data = {'a':0,'b':1,'c':2}
s = pd.Series(data)
print(s)

a    0
b    1
c    2
dtype: int64


In [14]:
data = {'a':0.,'b':1.,'c':2.}
s = pd.Series(data)
print(s)

a    0.0
b    1.0
c    2.0
dtype: float64


Urutan indeks bertahan dan element yang missing diisi dengan NaN (Not a Number)

In [15]:
data = {'a':0.,'b':1.,'c':2.}
s = pd.Series(data,index=['b','c','d','a'])
print(s)

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64


## Series dari Scalar
Jika data adalah nilai scalar, index harus disediakan. Nilai akan diulang sesuai dengan Panjang index

In [16]:
data = np.array(['a','b','c','d'])
s = pd.Series(5,index=[0,1,2,3])
print(s)

0    5
1    5
2    5
3    5
dtype: int64


Mengakses Data dari Series dengan Posisi

In [17]:
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s[0]) # mengambil elemen pertama
print()
print(s[:3]) # mengambil 3 elemen pertama
print()
print(s[-3:]) # mengambil 3 elemen terakhir
print()
print(s[['a','c','d']]) # Mengambil Data Menggunakan Label (index)

1

a    1
b    2
c    3
dtype: int64

c    3
d    4
e    5
dtype: int64

a    1
c    3
d    4
dtype: int64


## Pandas – Membuat DataFrame

In [18]:
df = pd.DataFrame()
print(df) # empty DataFrame

Empty DataFrame
Columns: []
Index: []


### DataFrame dari Lists

In [19]:
data = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [20]:
data = [['Alex',10],['Bob',12],['Clarke',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [21]:
df = pd.DataFrame(data,columns=['Name','Age'],dtype=float)
print(df)

     Name   Age
0    Alex  10.0
1     Bob  12.0
2  Clarke  13.0


### DataFrame dari Dict dari ndarray/Lists

In [22]:
data = {'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data)
print(df)

   Age   Name
0   28    Tom
1   34   Jack
2   29  Steve
3   42  Ricky


### Membuat index data frame menggunakan array

In [23]:
data = {'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,34,29,42]}
df = pd.DataFrame(data, index=['rank1','rank2','rank3','rank4'])
print(df)

       Age   Name
rank1   28    Tom
rank2   34   Jack
rank3   29  Steve
rank4   42  Ricky


### Membuat DataFrame dari List of Dict

In [24]:
data = [{'a': 1, 'b': 2},{'a': 5,'b': 10,'c': 20}]
df = pd.DataFrame(data)
print(df)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [25]:
data = [{'a': 1, 'b': 2},{'a': 5,'b': 10,'c': 20}]
df = pd.DataFrame(data, index=['first','second'])
print(df)

        a   b     c
first   1   2   NaN
second  5  10  20.0


### Membuat DataFrame dengan list of dictionary, indeks baris, dan indeks kolom

In [26]:
data = [{'a': 1, 'b': 2},{'a': 5,'b': 10,'c': 20}]
df1 = pd.DataFrame(data, index=['first','second'], columns=['a','b'])
df2 = pd.DataFrame(data, index=['first','second'], columns=['a','b1'])
print(df1)
print()
print(df2)

        a   b
first   1   2
second  5  10

        a  b1
first   1 NaN
second  5 NaN


### Membuat DataFrame dari Dict of Series

In [27]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4


### Menampilkan data base kolom dari DataFrame

In [28]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(d)
print(df['one'])

a    1.0
b    2.0
c    3.0
d    NaN
Name: one, dtype: float64


### Menambah kolom baru pada Data Frame yang sudah ada

In [29]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(d)

# menambah kolom baru pada DataFrame
print("menambah kolom baru pada DataFrame:")
df['three'] = pd.Series([10,20,30],index=['a','b','c'])
print(df)

# menambah kolom baru pada DataFrame dengan existing kolom
print("menambah kolom baru pada DataFrame dengan existing kolom:")
df['four'] = df['one']+df['three']
print(df)

menambah kolom baru pada DataFrame:
   one  two  three
a  1.0    1   10.0
b  2.0    2   20.0
c  3.0    3   30.0
d  NaN    4    NaN
menambah kolom baru pada DataFrame dengan existing kolom:
   one  two  three  four
a  1.0    1   10.0  11.0
b  2.0    2   20.0  22.0
c  3.0    3   30.0  33.0
d  NaN    4    NaN   NaN


### Menghapus kolom pada Data Frame

In [30]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d']),
    'three': pd.Series([10,20,30], index=['a','b','c'])}
df = pd.DataFrame(d)
print("Our dataframe is:")                       
print(df)
                       
# menghapus dengan del
print("menghapus kolom pertama pada DataFrame dgn DEL:")
del df['one']
print(df)

# menghapus dengan pop function
print("menghapus kolom lain pada DataFrame dgn POP func.:")
df.pop('two')
print(df)

Our dataframe is:
   one  three  two
a  1.0   10.0    1
b  2.0   20.0    2
c  3.0   30.0    3
d  NaN    NaN    4
menghapus kolom pertama pada DataFrame dgn DEL:
   three  two
a   10.0    1
b   20.0    2
c   30.0    3
d    NaN    4
menghapus kolom lain pada DataFrame dgn POP func.:
   three
a   10.0
b   20.0
c   30.0
d    NaN


### Pandas – Row Selection, Addition, Deletion

In [31]:
d = {'one': pd.Series([1,2,3], index=['a','b','c']),
    'two': pd.Series([1,2,3,4], index=['a','b','c','d'])}
df = pd.DataFrame(d)
print(df.loc['b'])

print()
# Selection by integer location dgn fungsi iloc
print(df.iloc[2])

print()
# Slice Rows – Multiple row dapat dipilih menggunakan operator ‘:’ 
print(df[2:4])

print()
# Addition of Rows– Penambahan baris baru ke DatFrame 
# menggunakan fungsi append, ini akan menambahkan baris 
# di bagian akhir
df2 = pd.DataFrame([[1,2],[3,4]], columns=['a','b'])
df3 = pd.DataFrame([[5,6],[7,8]], columns=['a','b'])

df2 = df2.append(df3)
print(df2)

print()
# Gunakan label indeks untuk menghapus baris dari DataFrame. 
# Jika terdapat label ganda, maka multiple rows akan dihapus
df2 = df2.drop(0) # menghapus row dgn label 0
print(df2)

one    2.0
two    2.0
Name: b, dtype: float64

one    3.0
two    3.0
Name: c, dtype: float64

   one  two
c  3.0    3
d  NaN    4

   a  b
0  1  2
1  3  4
0  5  6
1  7  8

   a  b
1  3  4
1  7  8


![title](img/thumbs-up.png)